<div class="row">
    <?php $no = 1;
    foreach ($data as $x) { ?>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="../img/<?= $x->foto ?>" alt="...">
                <div class="caption">
                    <h3>Thumbnail label</h3>
                    <p>...</p>
                    <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default"
                                                                                       role="button">Button</a></p>
                </div>
            </div>
        </div>
    <?php } ?>
</div>